[env]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense
framework = arduino
monitor_speed = 115200

lib_deps =
    bogde/HX711 @ ^0.7.5
    arduino-libraries/ArduinoBLE @ ^1.3.6

[env:xiaoble_left]
build_flags =
    -DPEDAL_IS_RIGHT_NODE=0

[env:xiaoble_right]
build_flags =
    -DPEDAL_IS_RIGHT_NODE=1
