[env]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
framework = arduino
monitor_speed = 115200

lib_deps =
    bogde/HX711 @ ^0.7.5
    arduino-libraries/ArduinoBLE @ ^1.3.6

[env:xiaoble_regular]
board = xiaoble
build_flags =
    -DPEDAL_IS_SENSE_NODE=0

[env:xiaoble_sense]
board = xiaoblesense
build_flags =
    -DPEDAL_IS_SENSE_NODE=1
