[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = no_ota.csv
monitor_speed = 115200
build_src_filter =
    +<*>
    -<pwm_motor_test.cpp>

lib_deps =
    br3ttb/PID @ ^1.2.1

[env:motor_pwm_test]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = no_ota.csv
monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF
monitor_filters = send_on_enter
build_src_filter =
    +<pwm_motor_test.cpp>
