[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = no_ota.csv
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    mikalhart/TinyGPSPlus @ ^1.0.3
    br3ttb/PID @ ^1.2.1
